"""
Django settings for SmartClassroom project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

## Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

## Quick-start development settings - unsuitable for production
## See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

## SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ctx&+8b0#wf^ce^j8n(gihd#^51_w*g2b8v%=$!1$%6)(6m-u^'

## SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

## Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SCControlSystem.apps.SmartClassroomConfig',
    'NodeHandler.apps.NodehandlerConfig',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SmartClassroom.urls'

TEMPLATES = [
    {
        'BACKEND':
        'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "template_require"),
            os.path.join(BASE_DIR, "template_reuse"),
            os.path.join(BASE_DIR, "template_callable"),
        ],
        'APP_DIRS':
        True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartClassroom.wsgi.application'

##Database
##https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sc_db',
        'USER': 'root',
        'PASSWORD': None,
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
            'isolation_level': 'read committed',
        },
    }
}

## Password validation
## https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

## Internationalization
## https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_L10N = True

USE_TZ = True

## Static files (CSS, JavaScript, Images)
## https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static_src/'

## The path where all static files will be collected, which to be placed here.
STATIC_ROOT = os.path.join(BASE_DIR, 'app_static_src')

## Additional Directory from where we collect static files. For instance, we have another folder that contains files to be candidated as a static resources for our app.
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_src')]

## User Model Extender
AUTH_USER_MODEL = 'SCControlSystem.UserDataCredentials'

## Folder Accessible for Additional Resources
MEDIA_URL = '/usersrc/'
