# Generated by Django 3.0.2 on 2020-01-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SC_ControlSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='commonId',
            field=models.CharField(default='oipEVtmp6ZPBhzu9IPfVQaEdx2NchLNm', max_length=32),
        ),
    ]
