# Generated by Django 3.0.2 on 2020-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SC_ControlSystem', '0002_auto_20200126_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='commonId',
            field=models.CharField(default='LV0AyWBUdLmIhDEoN6Iugu7XkUtAc8Yf', max_length=32),
        ),
    ]
