# Generated by Django 3.0.2 on 2020-01-25 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classroom_Name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)])),
                ('Classroom_Building', models.PositiveIntegerField(choices=[(1, 'Building 1'), (2, 'Building 2'), (3, 'Building 3'), (4, 'Building 4'), (5, 'Building 5'), (6, 'Building 6'), (7, 'Building 7'), (8, 'Building 8'), (9, 'Building 9'), (9, 'PE CNTR 1'), (10, 'PE CNTR 2')], default=(1, 'Building 1'))),
                ('Classroom_Floor', models.PositiveIntegerField(choices=[(1, 'Ground Floor'), (2, '2nd Floor'), (3, '3rd Floor'), (4, '4th Floor'), (5, '5th Floor')], default=(1, 'Ground Floor'))),
                ('Classroom_Number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(29)])),
                ('Classroom_Type', models.PositiveIntegerField(choices=[(0, 'Technology'), (1, 'Laboratory'), (2, 'External Env.')], default=(0, 'Technology'), unique=True)),
                ('Classroom_CompleteString', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='ProgramBranch',
            fields=[
                ('ProgramBranch_Name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)])),
                ('ProgramBranch_Description', models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255)])),
                ('ProgramBranch_Code', models.PositiveIntegerField(choices=[(0, 'Arch'), (1, 'CE'), (2, 'CpE'), (3, 'EE'), (4, 'ECE'), (5, 'EnSE'), (6, 'IE'), (7, 'ME')], primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_Name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)])),
                ('Course_Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(10)])),
                ('Course_Units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('Course_Capacity', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(60)])),
                ('Course_Type', models.CharField(choices=[(0, 'Technology'), (1, 'Laboratory'), (2, 'External Env.')], default=(0, 'Technology'), max_length=15, unique=True)),
            ],
            options={
                'unique_together': {('Course_Code', 'Course_Type')},
            },
        ),
        migrations.CreateModel(
            name='SectionGroup',
            fields=[
                ('Section_Name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)])),
                ('Section_Descrip', models.TextField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255)])),
                ('Section_Program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SmartClassroomInterface.ProgramBranch')),
                ('Section_Year', models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], unique=True)),
                ('Section_Semester', models.CharField(choices=[(1, '1st Semester'), (2, '2nd Semester')], max_length=15, unique=True)),
                ('Section_SubUniqueGrop', models.CharField(choices=[(0, 'FA1'), (1, 'FA2'), (2, 'FA3'), (3, 'FA4'), (4, 'FA5'), (5, 'FA6'), (7, 'FA7'), (8, 'FA8'), (9, 'FA9'), (10, 'FB1'), (11, 'FB2'), (12, 'FB3'), (13, 'FB4'), (14, 'FB5'), (15, 'FB6'), (17, 'FB7'), (18, 'FB8'), (19, 'FB9'), (20, 'FC1'), (21, 'FC2'), (22, 'FC3'), (23, 'FC4'), (24, 'FC5'), (25, 'FC6'), (27, 'FC7'), (28, 'FC8'), (29, 'FC9')], max_length=3, unique=True)),
                ('Section_CompleteStringGroup', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)])),
            ],
            options={
                'unique_together': {('Section_Program', 'Section_Year', 'Section_Semester', 'Section_SubUniqueGrop')},
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('CourseSchedule_CourseCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SmartClassroomInterface.Course')),
                ('CourseSchedule_Instructor', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50)])),
                ('CourseSchedule_LectureDay', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=(1, 'Monday'), max_length=10, unique=True)),
                ('CourseSchedule_SessionStart', models.TimeField(unique=True)),
                ('CourseSchedule_SessionEnd', models.TimeField(unique=True)),
            ],
            options={
                'unique_together': {('CourseSchedule_Instructor', 'CourseSchedule_LectureDay', 'CourseSchedule_SessionStart', 'CourseSchedule_SessionEnd')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserActionTaken', models.CharField(choices=[(0, 'Opened Classroom'), (1, 'Closed Classroom'), (2, 'Action: Automatically Set as Open on Time'), (3, 'Action: Automatically Set as Closed on Time'), (4, 'Authorized Staff Entry'), (5, 'Authorized Teacher Entry'), (6, 'Disabled Access Entry'), (7, 'Enabled Access Entry'), (8, 'Classroom Access is set to Disabled.'), (9, 'Classroom Access is Disabled.'), (10, 'Forbidden Attempt To Entry Detected.'), (11, 'Unauthorized Access Detected.')], max_length=255)),
                ('ClassRoom_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoomClassReference', to='SmartClassroomInterface.Classroom', to_field='Classroom_CompleteString')),
                ('ClassType_Reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TypeClassReference', to='SmartClassroomInterface.Classroom', to_field='Classroom_Type')),
                ('ClassInstructor_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InstructorAssociate', to='SmartClassroomInterface.CourseSchedule', to_field='CourseSchedule_Instructor')),
                ('Course_Reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CourseAssociated', to='SmartClassroomInterface.CourseSchedule')),
                ('LectureTimeEnd_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeEndEvent', to='SmartClassroomInterface.CourseSchedule', to_field='CourseSchedule_SessionEnd')),
                ('LectureTimeStart_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeStartEvent', to='SmartClassroomInterface.CourseSchedule', to_field='CourseSchedule_SessionStart')),
                ('Section_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentGroupAssociate', to='SmartClassroomInterface.SectionGroup', to_field='Section_CompleteStringGroup')),
            ],
        ),
    ]
