# Generated by Django 3.0.2 on 2020-01-26 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartClassroomInterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='Classroom_CompleteString',
            field=models.CharField(blank=True, error_messages={'unique': 'This generates conflits with existing values.'}, max_length=6, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='sectiongroup',
            name='Section_CompleteStringGroup',
            field=models.CharField(default=504, max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
