# Generated by Django 3.0.2 on 2020-01-10 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("Admin's First Name", models.CharField(max_length=20)),
                ("Admin's Middle Name", models.CharField(blank=True, max_length=20, null=True)),
                ("Admin's Last Name", models.CharField(max_length=50)),
                ("Admin's Age", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(75)])),
                ("Admin's Username", models.CharField(max_length=20)),
                ("Admin's Password", models.CharField(max_length=64)),
                ("Admin's Fingerprint", models.CharField(max_length=255)),
                ("Admin's Main Role", models.CharField(choices=[(1, 'ITSO Administrator'), (2, 'ITSO Assitant Administrator'), (3, 'ITSO Room Management')], default=(1, 'ITSO Administrator'), max_length=30)),
            ],
        ),
    ]
