# Generated by Django 3.0.2 on 2020-01-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminRoomControl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's Age",
            new_name='ads_AN',
        ),
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's First Name",
            new_name='ads_FN',
        ),
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's Last Name",
            new_name='ads_LN',
        ),
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's Middle Name",
            new_name='ads_MN',
        ),
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's Password",
            new_name='ads_PassP',
        ),
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's Main Role",
            new_name='ads_RoleT',
        ),
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's Fingerprint",
            new_name='ads_UserFP',
        ),
        migrations.RenameField(
            model_name='admindataset',
            old_name="Admin's Username",
            new_name='ads_UserP',
        ),
    ]
