# Generated by Django 3.0.3 on 2020-02-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='CourseSchedule_Unique_ID',
        ),
    ]
