# Generated by Django 3.0.2 on 2020-02-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Common_ID',
            field=models.CharField(default='YZGw85gC5YgalsPUgozsrJ6kpYY27UMO', max_length=32, unique=True),
        ),
    ]
