# Generated by Django 3.0.3 on 2020-02-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0002_auto_20200207_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='dept_residence',
            field=models.ForeignKey(default=None, help_text='Please refer the program code form where this staff resides.', on_delete=django.db.models.deletion.CASCADE, to='SCControlSystem.ProgramBranch', verbose_name='Staff Department Residence'),
            preserve_default=False,
        ),
    ]
