# Generated by Django 3.0.3 on 2020-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0002_auto_20200212_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomactionlog',
            name='TimeRecorded',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text="Refers to a time from where the log recorded someone's actions.", verbose_name='Log Action Recorded Time'),
            preserve_default=False,
        ),
    ]
