# Generated by Django 3.0.2 on 2020-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0002_auto_20200202_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Common_ID',
            field=models.CharField(default='xdIxCWeJJzjeaOFVIMH4hZS04GEHVDME', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userdatacredentials',
            name='User_Role',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Project Member', 'Project Member'), ('ITSO Administrator', 'ITSO Administrator'), ('ITSO Member', 'ITSO Member'), ('Professor Staff', 'Professor Staff'), ('Student Staff', 'Student Staff')], default=('Project Owner', 'Project Owner'), max_length=27),
        ),
        migrations.AlterField(
            model_name='userroletypes',
            name='RoleName',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Project Member', 'Project Member'), ('ITSO Administrator', 'ITSO Administrator'), ('ITSO Member', 'ITSO Member'), ('Professor Staff', 'Professor Staff'), ('Student Staff', 'Student Staff')], default=('Project Owner', 'Project Owner'), max_length=27),
        ),
    ]
