# Generated by Django 3.0.3 on 2020-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0003_auto_20200219_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='user_role',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Project Administrator', 'Project Administrator'), ('ITSO Administrator', 'ITSO Administrator'), ('ITSO Supervisor', 'ITSO Supervisor'), ('Professor', 'Professor')], default=('Project Owner', 'Project Owner'), help_text='Roles Defined that gives users multiple actions to do. Pick one with RISK.', max_length=27),
        ),
    ]
