# Generated by Django 3.0.3 on 2020-02-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0003_auto_20200212_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomactionlog',
            name='Course_Reference',
            field=models.ForeignKey(help_text='The course with its schedule referenced into one.', on_delete=django.db.models.deletion.CASCADE, to='SCControlSystem.CourseSchedule', verbose_name='Schedule Instance Reference'),
        ),
    ]
