# Generated by Django 3.0.2 on 2020-02-02 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0003_auto_20200202_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Common_ID',
            field=models.CharField(default='Gx6fHvaEUhlvKQQgtekfLpM2Vqxw9xPK', help_text='A Common Idenfitier for your Account. This is used for DB authentication and references.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Middle_Name',
            field=models.CharField(blank=True, help_text='A Name that is not supplied by User Model. Added for Unique User Purposes.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Unique_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A Unique Identifier for your Account. DO NOT SHARE IT OUTSIDE.'),
        ),
        migrations.AlterField(
            model_name='userdatacredentials',
            name='User_Role',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Project Member', 'Project Member'), ('ITSO Administrator', 'ITSO Administrator'), ('ITSO Member', 'ITSO Member'), ('Professor Staff', 'Professor Staff'), ('Student Staff', 'Student Staff')], default=('Project Owner', 'Project Owner'), help_text='Roles Defined that gives users multiple actions to do. Pick one with RISK.', max_length=27),
        ),
    ]
