# Generated by Django 3.0.2 on 2020-02-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0004_auto_20200202_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Common_ID',
            field=models.CharField(default='0mrPjY4kuP7SnZsdBCAEraSRdyMvGKC4', help_text='A Common Idenfitier for your Account. This is used for DB authentication and references.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userdatacredentials',
            name='User_Role',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Project Member', 'Project Member'), ('ITSO Administrator', 'ITSO Administrator'), ('ITSO Member', 'ITSO Member'), ('Professor Staff', 'Professor Staff')], default=('Project Owner', 'Project Owner'), help_text='Roles Defined that gives users multiple actions to do. Pick one with RISK.', max_length=27),
        ),
        migrations.AlterField(
            model_name='userroletypes',
            name='RoleName',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Project Member', 'Project Member'), ('ITSO Administrator', 'ITSO Administrator'), ('ITSO Member', 'ITSO Member'), ('Professor Staff', 'Professor Staff')], default=('Project Owner', 'Project Owner'), max_length=27),
        ),
    ]
