# Generated by Django 3.0.3 on 2020-02-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0005_auto_20200219_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='Classroom_AccessState',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', help_text='The current state of the classroom. This is very different from classroom device status.', max_length=8, verbose_name='Classroom Access State'),
        ),
    ]
