# Generated by Django 3.0.3 on 2020-02-08 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0005_auto_20200209_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sens_Name', models.CharField(help_text='Please indicate. We need to know what kind of sensors is it gonna be to communicate with the app.', max_length=100, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)], verbose_name='Sensors Name')),
                ('Sens_Type', models.CharField(choices=[('Digital Device', 'Digital Device'), ('Analog Device', 'Analog Device'), ('Security Device', 'Security Device')], default=('Digital Device', 'Digital Device'), help_text='The type of the sensors. This needs to be indicated to properly identify what kind of output it returns.', max_length=29, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(15)], verbose_name='Sensors Type')),
                ('Sens_Output', models.CharField(help_text='The output of the sensors can be a string, integer, float, or boolean.', max_length=255, verbose_name='Sensors Referred Output')),
            ],
            options={
                'verbose_name': 'Classroom Device Sensor Output',
                'db_table': 'dev_sens_output',
            },
        ),
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'verbose_name': 'Classroom MCU Device Information'},
        ),
        migrations.RemoveField(
            model_name='deviceinfo',
            name='Device_Description',
        ),
        migrations.RemoveField(
            model_name='deviceinfo',
            name='Device_Type',
        ),
        migrations.DeleteModel(
            name='DeviceOutput',
        ),
        migrations.AddField(
            model_name='sensoutput',
            name='Sens_Ref',
            field=models.ForeignKey(help_text='Indication of where the data comes from.', on_delete=django.db.models.deletion.CASCADE, to='SCControlSystem.DeviceInfo', to_field='Device_Unique_ID', verbose_name='Sensors Unique Reference'),
        ),
    ]
