# Generated by Django 3.0.2 on 2020-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0005_auto_20200204_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomactionlog',
            name='ActionLevel',
            field=models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Danger', 'Danger'), ('Alert', 'Alert')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroomactionlog',
            name='UserActionTaken',
            field=models.CharField(choices=[('Classroom is Opened.', 'Classroom is Opened.'), ('Classroom is Closed.', 'Classroom is Closed.'), ('Action: Automatically Set as Open on Time', 'Action: Automatically Set as Open on Time'), ('Action: Automatically Set as Closed on Time', 'Action: Automatically Set as Closed on Time'), ('Authorized Staff Entry', 'Authorized Staff Entry'), ('Authorized Teacher Entry', 'Authorized Teacher Entry'), ('Disabled Access Entry', 'Disabled Access Entry'), ('Enabled Access Entry', 'Enabled Access Entry'), ('Classroom Access is set to Disabled.', 'Classroom Access is set to Disabled.'), ('Classroom Access is Disabled.', 'Classroom Access is Disabled.'), ('Forbidden Attempt To Entry Detected.', 'Forbidden Attempt To Entry Detected.'), ('Unauthorized Access Detected.', 'Unauthorized Access Detected.')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Common_ID',
            field=models.CharField(default='LQ1oMnMqkZie9RmxmmAOxypzLwrqIEME', help_text='A Common Idenfitier for your Account. This is used for DB authentication and references.', max_length=32, unique=True),
        ),
    ]
