# Generated by Django 3.0.2 on 2020-02-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0006_auto_20200204_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatacredentials',
            name='Last_User_Created',
        ),
        migrations.AlterField(
            model_name='userdatacredentials',
            name='Common_ID',
            field=models.CharField(default='6SRzw8xCBtgABWjY33ZHAi0uVG3eov7t', help_text='A Common Idenfitier for your Account. This is used for DB authentication and references.', max_length=32, unique=True),
        ),
    ]
