# Generated by Django 3.0.3 on 2020-02-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0007_auto_20200209_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course Declaration'},
        ),
        migrations.AlterModelOptions(
            name='programbranch',
            options={'verbose_name': 'Department Program'},
        ),
        migrations.AlterModelOptions(
            name='userdatacredentials',
            options={'permissions': [('dashboard_viewable', 'Can view the dashboard itself. This must be allowed for everyone.')], 'verbose_name': 'User Credential'},
        ),
    ]
