# Generated by Django 3.0.3 on 2020-02-19 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0007_auto_20200219_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='Device_Status',
            field=models.CharField(
                choices=[('Online', 'Online'), ('Offline', 'Offline')],
                default='Unknown',
                help_text=
                'Status Indication of the device. Required. Basically this must match from the classroom status that is currently assigned with.',
                max_length=15,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(15)
                ],
                verbose_name='Device Status'),
        ),
    ]
