# Generated by Django 3.0.3 on 2020-02-25 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0010_auto_20200225_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='CourseSchedule_Lecture_Day',
            field=models.CharField(
                choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'),
                         ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'),
                         ('Friday', 'Friday'), ('Saturday', 'Saturday'),
                         ('Sunday', 'Sunday')],
                default=('Monday', 'Monday'),
                help_text=
                'Refers to a day in which the course session takes place.',
                max_length=9,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(9)
                ],
                verbose_name='Course Lecture Day'),
        ),
    ]
