# Generated by Django 3.0.3 on 2020-02-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0011_auto_20200225_1913'),
    ]

    operations = [
        migrations.DeleteModel(name='SensOutput', ),
    ]
