# Generated by Django 3.0.3 on 2020-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCControlSystem', '0013_auto_20200227_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomactionlog',
            name='UserActionTaken',
            field=models.CharField(choices=[('Classroom was Opened by Toggle Lock', 'Classroom was Opened by Toggle Lock'), ('Classroom was Closed by Toggle Lock', 'Classroom was Closed by Toggle Lock'), ('Classroom was Opened by Fingerprint', 'Classroom was Opened by Fingerprint'), ('Classroom Electricity was Turned On.', 'Classroom Electricity was Turned On.'), ('Classroom Electricity was Turned Of.', 'Classroom Electricity was Turned Off.'), ('Classroom was Closed by Fingerprint', 'Classroom was Closed by Fingerprint'), ('Classroom was Closed by Fingerprint', 'Classroom was Closed by Fingerprint'), ('Action: Set Room Automate to ON.', 'Action: Set Room Automate to ON.'), ('Action: Set Room Automate to OFF.', 'Action: Set Room Automate to OFF.'), ('Unauthorized Access Detected.', 'Unauthorized Access Detected.'), ('Authorized Access Passed.', 'Authorized Access Passed.'), ('Classroom Access was set to Disabled.', 'Classroom Access was set to Disabled.'), ('Classroom Access was set to Enabled.', 'Classroom Access was set to Enabled.')], help_text='A set of action taken by the stuff and user that is recently recorded by the system.', max_length=255, verbose_name='Staff / User Action Message'),
        ),
    ]
