# Generated by Django 3.0.2 on 2020-01-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRoomControl', '0002_auto_20200110_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdataset',
            old_name="User's First Name",
            new_name='sds_FN',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name="User's Last Name",
            new_name='sds_LN',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name="User's Middle Name",
            new_name='sds_MN',
        ),
        migrations.AddField(
            model_name='staffdataset',
            name='sds_Created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
